### ISSUE TITLE
When swipe to first position the onPageSelected is not called

### ISSUE THREAD

**Issue by kosaanta** [IslamKhSh/CardSlider#14]
If you swipe to position 0 the onPageSelected is not called thus the indicator doesn't select the first dot. This happens for the first page. e.g. If you setup the adapter and set viewPage.currentItem = 2 when you swipe to position 2 the onPageSelected is not called for this position and the indicator doesn't change.

**Comment by ulyrosas** [comment]
On file **ScrollEventAdapter.java** line **106** `mAdapterState != STATE_IN_PROGRESS_MANUAL_DRAG` causes a false positive.

Leave it like `if (newState == RecyclerView.SCROLL_STATE_DRAGGING)` will solve the problem.

**Comment by kosaanta** [comment]
@ulyrosas you are correct! You should make a pull request
