### ISSUE TITLE
ViewPager2

### ISSUE THREAD

**Issue by ZiraiMode** [IslamKhSh/CardSlider#2]
Hello. I really liked the functionality of your library, but there is one thing, it uses the first ViewPager. Are you planning to upgrade to ViewPager2? Thanks

**Comment by IslamKhSh** [comment]
Of course, ViewPager2 still in its beta version, once it comes to stable version I will use it.

**Comment by IslamKhSh** [comment]
Now CardSlider usues ViewPager2
