### ISSUE TITLE
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91 	is also present at [androidx.core:core:1.2.0-rc01] AndroidManifest.xml:24:18-86 value=(androidx.core.app.CoreComponentFactory). 	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:26:5-412:19 to override.

### ISSUE THREAD

**Issue by StevenStarz** [IslamKhSh/CardSlider#21]
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.2.0-rc01] AndroidManifest.xml:24:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:26:5-412:19 to override.

**Comment by StevenStarz** [comment]
@IslamKhSh

**Comment by StevenStarz** [comment]
Here is my gradle 

// Start One Signal
buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/' }
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.11.0, 0.99.99]'
    }
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

repositories {
    maven { url 'https://maven.google.com' }
}

// End One Signal


configurations {
    all {
        exclude module: 'httpclient'
    }
}
buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
        google()
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.+'
    }
}
apply plugin: 'com.android.application'
apply plugin: 'io.fabric'

allprojects {
    repositories {
        google()
        jcenter()
        google()
        maven {
            url 'http://www.idescout.com/maven/repo/'
        }
        maven { url "http://dl.bintray.com/pt-midtrans/maven" }
        maven { url 'https://maven.fabric.io/public' }
        maven { url 'https://maven.google.com' }
        maven { url "https://jitpack.io" }
    }
}
android {
    compileSdkVersion 28
    buildToolsVersion "28.0.3"
    useLibrary 'org.apache.http.legacy'
    defaultConfig {
        setProperty("archivesBaseName", "99 Virtual Race")
        flavorDimensions "default"
        multiDexEnabled true
        applicationId "id.compro.compro99virtualrace"
        minSdkVersion 19
        targetSdkVersion 28
        versionName "2.8.8"
        versionCode 208080
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        manifestPlaceholders = [
                onesignal_app_id               : "90639a02-3b5b-49f9-a1c7-0d3d320e8308",
                onesignal_google_project_number: "REMOTE"
        ]
    }
    configurations.all {
        resolutionStrategy.force 'com.google.code.findbugs:jsr305:2.0.1'
    }
    buildTypes {
        debug {
//            // Disable fabric build ID generation for debug builds
//            ext.enableCrashlytics = false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            zipAlignEnabled false
        }
    }
    // Define Merchant BASE URL and CLIENT KEY for each flavors
    productFlavors {
        production {
            buildConfigField "String", "BASE_URL", "\"https://merchant-url-production.com\""
            buildConfigField "String", "CLIENT_KEY", "\"VT-CLIENT-production-client-key\""
        }
//        sandbox {
//            buildConfigField "String", "BASE_URL", "\"https://merchant-url-sandbox.com/\""
//            buildConfigField "String", "CLIENT_KEY", "\"VT-CLIENT-sandbox-client-key\""
//        }
    }

    dexOptions {
        javaMaxHeapSize "4g"
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    implementation project(path: ':SwipeableLayout')
    implementation project(path: ':bottomsheet')
    implementation files('libs/activation.jar')
    implementation files('libs/additionnal.jar')
    implementation files('libs/mail.jar')

    // Support Librariesx
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:support-v4:28.0.0'
    implementation 'com.android.support:design:28.0.0'
    implementation 'com.android.support:support-v13:28.0.0'
    implementation 'com.android.support:cardview-v7:28.0.0'
    implementation 'com.android.support:recyclerview-v7:28.0.0'
    implementation 'com.android.support:multidex:1.0.1'

    // Custom ListView
    implementation 'com.nhaarman.listviewanimations:lib-core:3.1.0@aar'
    implementation 'com.nhaarman.listviewanimations:lib-manipulation:3.1.0@aar'
    implementation 'com.nhaarman.listviewanimations:lib-core-slh:3.1.0@aar'

    // Http Service
    implementation 'com.android.volley:volley:1.1.0'


    // Image Libraries
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.github.chrisbanes:PhotoView:2.1.3'
    compile 'com.nineoldandroids:library:2.4.0'
    compile 'com.github.bumptech.glide:glide:3.7.0'
    compile 'pl.droidsonroids.gif:android-gif-drawable:1.2.+'
    compile 'com.daimajia.swipelayout:library:1.2.0@aar'
    compile 'com.github.okaybroda:ImageZoom:1.1.0'

    // SQLScout
    compile 'com.idescout.sql:sqlscout-server:4.0'

    // Maps
    compile 'com.google.android.gms:play-services-maps:15.0.1'
    compile 'com.google.maps.android:android-maps-utils:0.5'

    // Midtrans
//    compile 'com.midtrans:uikit:1.23.1-SANDBOX'
    compile 'com.midtrans:uikit:1.23.1'

    // Tracking
//    compile project(':react-native-background-geolocation')
//    compile project(':react-native-background-fetch')
//    compile project(':react-native-device-info')
//    compile project(':react-native-prompt-android')
//    compile project(':react-native-vector-icons')
//    compile(project(':react-native-maps')) {
//        exclude group: 'com.google.android.gms', module: 'play-services-base'
//        exclude group: 'com.google.android.gms', module: 'play-services-maps'
//    }
//    compile project(":react-native-shared-preferences")
//    compile project(':react-native-background-timer')

    // Other
    compile 'com.miguelcatalan:materialsearchview:1.4.0'
    implementation 'com.onesignal:OneSignal:[3.9.1, 3.99.99]'

    implementation 'com.android.support.constraint:constraint-layout:1.1.2'

    compile 'com.iceteck.silicompressorr:silicompressor:2.1'
    compile 'com.sweetzpot.stravazpot:lib:1.3.1'
    compile 'com.github.vipulasri:timelineview:1.0.6'
    compile 'com.andreabaccega:android-form-edittext:1.3.+'
    compile 'com.github.arimorty:floatingsearchview:2.1.1'
    compile 'me.himanshusoni.quantityview:quantity-view:1.2.0'
    compile 'com.facebook.react:react-native:+'
    implementation 'com.alimuzaffar.lib:pinentryedittext:1.3.10'

    // Facebook
    implementation 'com.facebook.android:facebook-android-sdk:[5,6)'

    // Google
    compile 'com.google.api-client:google-api-client:1.22.0'
    compile 'com.google.api-client:google-api-client-android:1.22.0'
    compile 'com.google.apis:google-api-services-people:v1-rev4-1.22.0'

    // CrashLytics
    compile('com.crashlytics.sdk.android:crashlytics:2.7.1@aar') {
        transitive = true;
        exclude group: 'com.android.support', module: 'support-annotations'
    }

    // OneSignal
    def gmsVersion = '15.0.1'
    compile("com.google.android.gms:play-services-gcm:${gmsVersion}") {
        force = true
    }
    compile("com.google.android.gms:play-services-auth:15.0.1")
    compile("com.google.android.gms:play-services-plus:15.0.1")

    compile("com.google.android.gms:play-services-location:${gmsVersion}") {
        force = true
    }
    // Must use 26.0.0 or newer if you have targetSdkVersion 26
    def androidSupportVersion = '27.1.1'
    compile("com.android.support:support-v4:${androidSupportVersion}") {
        force = true
    }
    compile("com.android.support:customtabs:${androidSupportVersion}") {
        force = true
    }

    implementation 'com.jakewharton:butterknife:8.5.1'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.5.1'
    implementation 'com.github.IslamKhSh:CardSlider:1.0.1'

    testCompile 'junit:junit:4.12'
}

**Comment by IslamKhSh** [comment]
Try this solution
https://stackoverflow.com/a/50965002/4760639

Feel free to reopen  it again if the issue not resolved
