### ISSUE TITLE
Request to support dotsindicatory library

### ISSUE THREAD

**Issue by radheyshyamjat** [IslamKhSh/CardSlider#24]
I'm implement other library for indicate dot's
Previous version in support this library but new update library in not support
0.4 version support 1.0.1 not support

Please support
[https://github.com/tommybuonomo/dotsindicator](url)

**Comment by IslamKhSh** [comment]
since version 1.0.0 https://github.com/IslamKhSh/CardSlider/commit/e58af2ee39456321ec0869d73dcbf912ba1a63f7 card slider uses ViewPager2 so you can't use setViewPager method in dotsindicator library alternatively use setViewPager2 method

**Comment by radheyshyamjat** [comment]
Yes i checked setViewPage2 method also that also not support
