### ISSUE TITLE
notifyDataSetChanged() not update the data

### ISSUE THREAD

**Issue by borombo-git** [IslamKhSh/CardSlider#3]
Hello, 
First, thanks for this amazing lib, you saved me a ton of time!
I started to implement it, and I noticed that when I call notifyDataSetChanged on the adapter, the list is not refreshed, is it normal? 
Thanks !

**Comment by IDevelopes** [comment]
Im getting the same issue

**Comment by maherzaidoune** [comment]
override getItemPosition method and call 
`
@Override
    public int getItemPosition(@NonNull Object object) {
        return POSITION_NONE;
    }`
inside your adapter will solve the problem

**Comment by IDevelopes** [comment]
Im still getting this error `The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 4, found: 0`. I get this error when i open new activity then i return to previous. Thanks

**Comment by IslamKhSh** [comment]
This is a bug in the library as data can't set after adapter initiated.
You can get it fixed within few days

**Comment by IslamKhSh** [comment]
Fixed  e58af2ee39456321ec0869d73dcbf912ba1a63f7  (v1.0.0)
