### ISSUE TITLE
Jcenter

### ISSUE THREAD

**Issue by m5kh6n77** [IslamKhSh/CardSlider#41]
jcenter is shutdown please migrate to maven central

**Comment by cyb3rko** [comment]
You can use Jitpack if you want to. See here:
https://jitpack.io/#IslamKhSh/CardSlider

**Comment by m5kh6n77** [comment]
> You can use Jitpack if you want to. See here:
> https://jitpack.io/#IslamKhSh/CardSlider

thank you
