### ISSUE TITLE
Using card slider adapter with live data

### ISSUE THREAD

**Issue by ruthwikkk** [IslamKhSh/CardSlider#6]
Hi,
Thanks for the repo. It's very useful. 
Recently I have migrated my app to MVVM.
One of my CardSliderAdapter use livedata as the source. Is there any way to add items to Adapter after creating/instantiating the adapter object like in paged recycler adapter?

**Comment by IslamKhSh** [comment]
This is a bug in the library as data can't set after adapter initiated. 
You can get it fixed within few days

**Comment by IslamKhSh** [comment]
you can follow the issue here #3
