### ISSUE TITLE
Full screen Y axis has a downward offset

### ISSUE THREAD

**Issue by Khaos116** [IslamKhSh/CardSlider#7]
![image](https://user-images.githubusercontent.com/11989916/66639214-a281fa00-ec40-11e9-8361-93fa068e6028.png)

**Comment by Khaos116** [comment]
@IslamKhSh

**Comment by ruthwikkk** [comment]
@caiyoufei I had the same issue. I switched from Constrained layout to Linear layout and its working good

**Comment by Khaos116** [comment]
@ruthwikkk thanks

**Comment by IslamKhSh** [comment]
This issue is basically from viewPager itself, there are some workarounds to avoid this but for now I prefer to replace ViewPager with ViewPager2 as soon as possible.

**Comment by IslamKhSh** [comment]
Fixed  e58af2ee39456321ec0869d73dcbf912ba1a63f7  (v1.0.0)
